#!/usr/bin/env python3
"""Create Hypertrader user activity dashboard (user_id=1).

Thin declarative spec on top of rewatch.assistant.dashboard_builder. This
refactor also fixes the original text-widget bug where section headers were
inserted with NULL text.
"""

from __future__ import annotations

from dashboard_script_utils import build_and_report

DS = 12
HT_USER_ID = 1


def q(name: str, description: str, sql: str, viz: list[dict]) -> dict:
    return {
        "name": name,
        "description": description,
        "data_source_id": DS,
        "query": sql.strip(),
        "visualizations": viz,
    }


def counter(name: str, column: str, label: str = "") -> dict:
    return {"type": "COUNTER", "name": name, "counter_column": column, "counter_label": label}


def chart(name: str, chart_type: str, mapping: dict) -> dict:
    return {"type": "CHART", "name": name, "chart_type": chart_type, "column_mapping": mapping}


QUERIES = [
    q(
        "Hypertrader User - Activity Summary",
        "Key activity totals for the primary Hypertrader user.",
        f"""
SELECT
  (SELECT COUNT(*) FROM saved_backtests WHERE user_id = {HT_USER_ID})::int AS total_backtests,
  (SELECT COUNT(*) FROM swarm_findings WHERE user_id = {HT_USER_ID})::int AS swarm_findings,
  (SELECT COUNT(*) FROM strategies WHERE user_id = {HT_USER_ID})::int AS strategies,
  (SELECT COUNT(*) FROM swarms WHERE user_id = {HT_USER_ID} AND status = 'running')::int AS swarms_running,
  (SELECT COUNT(*) FROM agents WHERE user_id = {HT_USER_ID})::int AS agents,
  (SELECT COUNT(*) FROM chat_messages cm JOIN chat_threads ct ON ct.id = cm.thread_id WHERE ct.user_id = {HT_USER_ID})::int AS chat_messages,
  (SELECT COUNT(*) FROM strategy_events se JOIN strategies s ON s.id = se.strategy_id WHERE s.user_id = {HT_USER_ID})::int AS strategy_events,
  (SELECT COUNT(*) FROM agent_events ae JOIN agents a ON a.id = ae.agent_id WHERE a.user_id = {HT_USER_ID})::int AS agent_events
""",
        [
            counter("Total Backtests", "total_backtests"),
            counter("Swarm Findings", "swarm_findings"),
            counter("Strategies", "strategies"),
            counter("Swarms Running", "swarms_running"),
            counter("AI Agents", "agents"),
            counter("Chat Messages", "chat_messages"),
            counter("Strategy Events", "strategy_events"),
            counter("Agent Events", "agent_events"),
        ],
    ),
    q(
        "Hypertrader User - Swarm Findings per Day",
        "Daily volume of swarm strategy discoveries.",
        f"SELECT created_at::date AS day, COUNT(*)::int AS findings\nFROM swarm_findings\nWHERE user_id = {HT_USER_ID}\nGROUP BY 1\nORDER BY 1",
        [chart("Findings per Day", "line", {"day": "x", "findings": "y"})],
    ),
    q(
        "Hypertrader User - Backtests per Day",
        "Daily backtest runs generated by swarms.",
        f"SELECT created_at::date AS day, COUNT(*)::int AS backtests\nFROM saved_backtests\nWHERE user_id = {HT_USER_ID}\nGROUP BY 1\nORDER BY 1",
        [chart("Backtests per Day", "area", {"day": "x", "backtests": "y"})],
    ),
    q(
        "Hypertrader User - Findings by Strategy Type",
        "Swarm findings grouped by strategy archetype.",
        f"SELECT strategy_type, COUNT(*)::int AS findings\nFROM swarm_findings\nWHERE user_id = {HT_USER_ID}\nGROUP BY 1\nORDER BY 2 DESC",
        [chart("Findings by Type", "column", {"strategy_type": "x", "findings": "y"})],
    ),
    q(
        "Hypertrader User - Avg Return by Type",
        "Average simulated return by strategy type across all backtests.",
        f"""
SELECT type AS strategy_type,
  COUNT(*)::int AS backtests,
  ROUND(AVG((stats->>'return_pct')::float)::numeric, 2) AS avg_return_pct
FROM saved_backtests
WHERE user_id = {HT_USER_ID} AND stats->>'return_pct' IS NOT NULL
GROUP BY 1
ORDER BY 3 DESC
""",
        [chart("Avg Return by Type", "column", {"strategy_type": "x", "avg_return_pct": "y"})],
    ),
    q(
        "Hypertrader User - Strategies by Status",
        "Current strategy fleet status breakdown.",
        f"SELECT status, COUNT(*)::int AS count\nFROM strategies\nWHERE user_id = {HT_USER_ID}\nGROUP BY 1\nORDER BY 2 DESC",
        [chart("Strategies by Status", "pie", {"status": "x", "count": "y"})],
    ),
    q(
        "Hypertrader User - Strategy Events per Day",
        "Bot runtime events over time by kind.",
        f"""
SELECT se.created_at::date AS day, se.kind, COUNT(*)::int AS events
FROM strategy_events se
JOIN strategies s ON s.id = se.strategy_id
WHERE s.user_id = {HT_USER_ID}
GROUP BY 1, 2
ORDER BY 1
""",
        [chart("Strategy Events per Day", "line", {"day": "x", "events": "y", "kind": "series"})],
    ),
    q(
        "Hypertrader User - Strategy Event Mix",
        "Distribution of strategy runtime event kinds.",
        f"""
SELECT se.kind, COUNT(*)::int AS events
FROM strategy_events se
JOIN strategies s ON s.id = se.strategy_id
WHERE s.user_id = {HT_USER_ID}
GROUP BY 1
ORDER BY 2 DESC
""",
        [chart("Event Mix", "pie", {"kind": "x", "events": "y"})],
    ),
    q(
        "Hypertrader User - Top Strategies by Events",
        "Strategies with the most runtime events.",
        f"""
SELECT s.name, s.type, s.status, COUNT(se.id)::int AS events
FROM strategies s
LEFT JOIN strategy_events se ON se.strategy_id = s.id
WHERE s.user_id = {HT_USER_ID}
GROUP BY s.id, s.name, s.type, s.status
ORDER BY events DESC
LIMIT 15
""",
        [chart("Top Strategies", "column", {"name": "x", "events": "y"})],
    ),
    q(
        "Hypertrader User - Agent Events Timeline",
        "AI agent decision and info events over time.",
        f"""
SELECT ae.created_at::date AS day, ae.kind, COUNT(*)::int AS events
FROM agent_events ae
JOIN agents a ON a.id = ae.agent_id
WHERE a.user_id = {HT_USER_ID}
GROUP BY 1, 2
ORDER BY 1
""",
        [chart("Agent Events Timeline", "column", {"day": "x", "events": "y", "kind": "series"})],
    ),
    q(
        "Hypertrader User - Chat Activity per Day",
        "Daily assistant chat message volume.",
        f"""
SELECT cm.created_at::date AS day, COUNT(*)::int AS messages
FROM chat_messages cm
JOIN chat_threads ct ON ct.id = cm.thread_id
WHERE ct.user_id = {HT_USER_ID}
GROUP BY 1
ORDER BY 1
""",
        [chart("Chat per Day", "line", {"day": "x", "messages": "y"})],
    ),
    q(
        "Hypertrader User - Top Backtests",
        "Best-performing backtests by return %.",
        f"""
SELECT coin, type, LEFT(name, 80) AS name,
  ROUND((stats->>'return_pct')::numeric, 2) AS return_pct,
  ROUND((stats->>'max_drawdown_pct')::numeric, 2) AS max_dd_pct,
  (stats->>'trades')::int AS trades,
  created_at::timestamp AS created_at
FROM saved_backtests
WHERE user_id = {HT_USER_ID} AND stats->>'return_pct' IS NOT NULL
ORDER BY (stats->>'return_pct')::float DESC
LIMIT 50
""",
        [{"type": "TABLE", "name": "Top Backtests"}],
    ),
    q(
        "Hypertrader User - My Strategies",
        "All strategies owned by the user.",
        f"SELECT id, name, coin, type, status, network, created_at::date AS created\nFROM strategies\nWHERE user_id = {HT_USER_ID}\nORDER BY created_at DESC",
        [{"type": "TABLE", "name": "My Strategies"}],
    ),
    q(
        "Hypertrader User - My Agents",
        "AI trading agents configured by the user.",
        f"SELECT id, name, coin, model, provider, status, interval_minutes, created_at::date AS created\nFROM agents\nWHERE user_id = {HT_USER_ID}\nORDER BY created_at",
        [{"type": "TABLE", "name": "My Agents"}],
    ),
    q(
        "Hypertrader User - My Swarms",
        "Active and historical swarm research jobs.",
        f"SELECT id, name, status, num_agents, interval_hours, coins::text AS coins, created_at::date AS created\nFROM swarms\nWHERE user_id = {HT_USER_ID}\nORDER BY id",
        [{"type": "TABLE", "name": "My Swarms"}],
    ),
    q(
        "Hypertrader User - Recent Strategy Events",
        "Latest bot runtime log entries.",
        f"""
SELECT se.created_at, s.name AS strategy, se.kind, LEFT(se.message, 120) AS message
FROM strategy_events se
JOIN strategies s ON s.id = se.strategy_id
WHERE s.user_id = {HT_USER_ID}
ORDER BY se.created_at DESC
LIMIT 100
""",
        [{"type": "TABLE", "name": "Recent Events"}],
    ),
    q(
        "Hypertrader User - Chat Threads",
        "Assistant conversation threads and message counts.",
        f"""
SELECT LEFT(ct.title, 100) AS title,
  ct.created_at::date AS created,
  COUNT(cm.id)::int AS messages,
  ct.updated_at::date AS last_active
FROM chat_threads ct
LEFT JOIN chat_messages cm ON cm.thread_id = ct.id
WHERE ct.user_id = {HT_USER_ID}
GROUP BY ct.id, ct.title, ct.created_at, ct.updated_at
ORDER BY ct.updated_at DESC
""",
        [{"type": "TABLE", "name": "Chat Threads"}],
    ),
]


def pos(col: int, row: int, size_x: int, size_y: int) -> dict:
    return {"col": col, "row": row, "sizeX": size_x, "sizeY": size_y}


WIDGETS = [
    {
        "text": "# Hypertrader — Your Activity\n\nPersonal trading research, swarm discovery, bot fleet, and assistant usage for **0x2afe…b6cf** (owner, desk plan).",
        "position": pos(0, 0, 12, 3),
    },
    {"text": "## Activity at a Glance", "position": pos(0, 3, 12, 2)},
    {"visualization": "Total Backtests", "position": pos(0, 5, 3, 8)},
    {"visualization": "Swarm Findings", "position": pos(3, 5, 3, 8)},
    {"visualization": "Strategies", "position": pos(6, 5, 3, 8)},
    {"visualization": "Swarms Running", "position": pos(9, 5, 3, 8)},
    {"visualization": "AI Agents", "position": pos(0, 13, 3, 8)},
    {"visualization": "Chat Messages", "position": pos(3, 13, 3, 8)},
    {"visualization": "Strategy Events", "position": pos(6, 13, 3, 8)},
    {"visualization": "Agent Events", "position": pos(9, 13, 3, 8)},
    {
        "text": "## Swarm Research Engine\n\n764k+ backtests and swarm findings from 8 running discovery swarms.",
        "position": pos(0, 21, 12, 2),
    },
    {"visualization": "Findings per Day", "position": pos(0, 23, 8, 8)},
    {"visualization": "Findings by Type", "position": pos(8, 23, 4, 8)},
    {"visualization": "Backtests per Day", "position": pos(0, 31, 8, 8)},
    {"visualization": "Avg Return by Type", "position": pos(8, 31, 4, 8)},
    {"visualization": "Top Backtests", "position": pos(0, 39, 12, 8)},
    {"text": "## Bots & Live Trading", "position": pos(0, 47, 12, 2)},
    {"visualization": "Strategy Events per Day", "position": pos(0, 49, 8, 8)},
    {"visualization": "Event Mix", "position": pos(8, 49, 4, 8)},
    {"visualization": "Top Strategies", "position": pos(0, 57, 6, 8)},
    {"visualization": "Strategies by Status", "position": pos(6, 57, 6, 8)},
    {"visualization": "Agent Events Timeline", "position": pos(0, 65, 6, 8)},
    {"visualization": "Chat per Day", "position": pos(6, 65, 6, 8)},
    {"text": "## Fleet & Logs", "position": pos(0, 73, 12, 2)},
    {"visualization": "My Strategies", "position": pos(0, 75, 6, 8)},
    {"visualization": "My Agents", "position": pos(6, 75, 6, 8)},
    {"visualization": "My Swarms", "position": pos(0, 83, 6, 8)},
    {"visualization": "Recent Events", "position": pos(6, 83, 6, 8)},
    {"visualization": "Chat Threads", "position": pos(0, 91, 12, 6)},
]


if __name__ == "__main__":
    build_and_report(name="Hypertrader User Activity", queries=QUERIES, widgets=WIDGETS)
