import * as echarts from "echarts/core";
import {
  BarChart,
  LineChart,
  PieChart,
  ScatterChart,
  EffectScatterChart,
  RadarChart,
  TreeChart,
  TreemapChart,
  SunburstChart,
  BoxplotChart,
  CandlestickChart,
  HeatmapChart,
  MapChart,
  ParallelChart,
  LinesChart,
  GraphChart,
  SankeyChart,
  FunnelChart,
  GaugeChart,
  PictorialBarChart,
  ThemeRiverChart,
} from "echarts/charts";
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  VisualMapComponent,
  ToolboxComponent,
  TitleComponent,
  GraphicComponent,
  DatasetComponent,
  TransformComponent,
  RadarComponent,
  ParallelComponent,
  SingleAxisComponent,
  TimelineComponent,
  CalendarComponent,
} from "echarts/components";
import { CanvasRenderer } from "echarts/renderers";

import "echarts-wordcloud";

echarts.use([
  BarChart,
  LineChart,
  PieChart,
  ScatterChart,
  EffectScatterChart,
  RadarChart,
  TreeChart,
  TreemapChart,
  SunburstChart,
  BoxplotChart,
  CandlestickChart,
  HeatmapChart,
  MapChart,
  ParallelChart,
  LinesChart,
  GraphChart,
  SankeyChart,
  FunnelChart,
  GaugeChart,
  PictorialBarChart,
  ThemeRiverChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  VisualMapComponent,
  ToolboxComponent,
  TitleComponent,
  GraphicComponent,
  DatasetComponent,
  TransformComponent,
  RadarComponent,
  ParallelComponent,
  SingleAxisComponent,
  TimelineComponent,
  CalendarComponent,
  CanvasRenderer,
]);

export default echarts;
